apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - cassandra-service.yaml
  - cassandra-statefulset.yaml
  - minio-service.yaml
  - minio-statefulset.yaml
  - trino-deployment.yaml
  - api-deployment.yaml
  - ui-deployment.yaml
  - job-generate-data.yaml
  - job-run-pipeline.yaml
