apiVersion: v1
kind: Secret
metadata:
  name: retail-risk-secret
  namespace: retail-risk
type: Opaque
stringData:
  CASSANDRA_USERNAME: retail
  CASSANDRA_PASSWORD: retail
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
